FROM node:22-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./apps/worker ./apps/worker

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN npm install -g pnpm
RUN pnpm install

RUN pnpm build

CMD ["pnpm", "run", "start:worker"]